### ISSUE TITLE
Prepare material for Roche demonstration of Shiny tool and collaboration portal bi-directional communication

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sagebio-collaboration-portal#160]
This ticket provides step-by-step instructions on how to present the bi-directional communication between the PHCCP Shiny Tool Example and the Collaboration portal.

## Features that can currently be demonstrated

- [x] Open the Shiny app and load it with data selected from the collaboration portal
- [x] Save the Shiny app state to the collaboration portal
- [x] Open the Shiny app and restore a state from the collaboration portal

Unchecked features are currently under development.

## Resources
- [PHC Collaboration Portal (test server)](test.phc.sagesandbox.org)
- [PHCCP Shiny Tool Example](https://phccp-shiny.synapse.org/develop/app/)

## Demo
- Log in into the collaboration portal and provide an overview
  - For this demo, make sure to present the concept of Projects and Insights
- Go to [PHCCP Shiny Tool Example](https://phccp-shiny.synapse.org/develop/app/)
- Modify the controls of the Shiny app
- Click on the Save State button
- Set a name, description, and select one of the Projects listed in the collaboration portal
- Click OK
- Go back to the collaboration portal, locate the State item under the Insights tab, and go to the page of the State
- Show that description can be updated. For example, copy paste the content of a short Word document to show that the formatting is conserved. Also, consider adding a small image. Click on the button Update Description.
- Click on Open With PHCCP Shiny Tool Example. A new tab will open in the browser with the Shiny app state restored.

## Notes

Consider providing information to the audience on these upcoming feature

- Authentication to the Shiny app will be added at a later time. When this feature is added, the State saved to the collaboration portal will show who has saved it. For now this value is hard coded in the portal to "Thomas".
- For now, the Shiny app lists all the projects created in the collaboration portal. When the portal will enable users to join a project AND Shiny app support authentication/authorization, then a State will be effectively associated to a project.

## TODO before presenting this demo

- [x] Modify the PHCCP Shiny Tool Example so that it queries the test portal (currently targets the dev portal)
