### ISSUE TITLE
EPIC: enable basic provenance capture for selected activities

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/sagebio-collaboration-portal#457]
A lot of the pieces should now be in place to create and visualize provenance (i.e., activity) within the portal. Next steps are to (1) automate provenance capture for certain activities (e.g., creating a `Report` that references some `Resource`); (2) improve functionality of components for manually registering activities (e.g., better integration with other portal services and entities); and (3) clean up the graph visualization and associated controls to the point of an MVP widget — something legible and at least slightly useful/interesting.

There might be some additional tickets to add here as we go (including for updates to the [`prov-service`](https://github.com/Sage-Bionetworks/prov-service) app as well)

#### Critical tickets:

- [x] **#357: Create new activities for certain user actions within the portal** — This describes the main types and model for activities we want to capture. The types are roughly in order of complexity: I'd say 1 and 2 are the best place to start, 3 would be "nice to have" and 4 is likely out of scope for this phase.
- [x] **#367: Allow users to create/register activities connected to a particular entity (Insight, Resource, Tool, etc.)** — This addresses the addition of a form to manually record and save an activity in provenance. #431 and #437 *mostly* fix this, but behavior is a bit clunky. For example, it'd be nice to "look up" used and generated entities via the corresponding service, rather than just enter a name/ID in a text field. 
- [x] **#288: Create component to capture activity for provenance** — This is more focused on automating some of the above steps (#367 was useful to sort out what information and formats are needed for the provenance API). @Stanley-Jovel made some progress with the `CaptureProvenanceActivityService`, which wraps `POST` calls for new `Resource` or `Insight` records... but I'm not sure if it's working at the moment.

---

#### Related maintenance tickets:

- [x] **#439: Make provenance graph SVG size responsive**
- [x] **#451: ERROR TypeError: Cannot read property 'simulation' of undefined**
- [x] **#440: Fix reactivity in provenance/activity components**

On a related note, we currently have provenance-related components divided into models/components/services for `provenance` and `activity`. While this structure made some sense earlier, it could be worth combining.
